version: '3.8'

services:
  app:
    build: .
    ports:
      - "1000:1000"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/yourdatabase
      - SPRING_DATASOURCE_USERNAME=youruser
      - SPRING_DATASOURCE_PASSWORD=yourpassword
      - JWT_SECRET_KEY=${JWT_SECRET_KEY} # Example: passing through from host .env or set directly
      - SUPPORT_EMAIL=${SUPPORT_EMAIL}
      - APP_PASSWORD=${APP_PASSWORD}
    depends_on:
      - db
    networks:
      - spring-net

  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=yourdatabase
      - POSTGRES_USER=youruser
      - POSTGRES_PASSWORD=yourpassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - spring-net

volumes:
  postgres_data:

networks:
  spring-net:
    driver: bridge
